### ISSUE TITLE
Identifier rejected

### ISSUE THREAD

**Issue by AdeTheux** [joe-ng/homebridge-dyson-link#112]
It's been working flawlessly for many months, but since a few days, I have random homebridge crashes apparently linked to the Dyson-link plugin:
`Error: Connection refused: Identifier rejected
    at MqttClient._handleConnack (/data/data/com.termux/files/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:877:15)
    at MqttClient._handlePacket (/data/data/com.termux/files/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:319:12)
    at work (/data/data/com.termux/files/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/data/data/com.termux/files/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/data/data/com.termux/files/usr/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/data/data/com.termux/files/usr/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/data/data/com.termux/files/usr/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:745:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:325:12)
    at readableAddChunk (_stream_readable.js:300:11)
    at Socket.Readable.push (_stream_readable.js:234:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23`

**Comment by AdeTheux** [comment]
Can I try and get more logs about this issue to help debugging it? Issue still happens regularly unfortunately.

**Comment by donavanbecker** [comment]
I haven't seen @joe-ng on GitHub for a while.. might be worth checking out [homebridge-dyson-pure-cool](https://github.com/lukasroegner/homebridge-dyson-pure-cool#readme)

**Comment by AdeTheux** [comment]
I'll try that plugin instead, thanks!
