### ISSUE TITLE
Remove devices created by this plugin?

### ISSUE THREAD

**Issue by twynne** [joe-ng/homebridge-dyson-link#113]
Hi,

I’ve discontinued use of this plugin, but the devices created seem to persist and there is no option within HomeKit/Home app to delete them. Is there some way to get rid of these devices that are no longer functional?

**Comment by donavanbecker** [comment]
What version of homebridge are you on?

**Comment by twynne** [comment]
0.4.53

I’ve stayed clear of 1.x for the moment.

**Comment by donavanbecker** [comment]
First question:
- Why have you stayed clear of v1.0.0?
Second question:
- are you using Config UI X?

**Comment by twynne** [comment]
> First question:
>
> * Why have you stayed clear of v1.0.0

Reports of issues with it

>   Second question:
> * are you using Config UI X?

Yes

**Comment by donavanbecker** [comment]
> Reports of issues with it
- these are only happening in certain situations and you can always roll back to 0.4.53. But upgrading and trying it helps all. If you have issues you can report them and then rollback. if you don't have issues, then perfect you are good to go. 
- just think about.. :)
> Yes
- perfect there is actually a switch in there where you can remove cached accessories from removed plugins, if you click the 3 dots in the upper right and then click homebridge settings. Click the remove accessories of uninstalled plugins. that should be checked and then restart.
- report back if it works or not?
<img width="1241" alt="Screen Shot 2020-04-28 at 8 58 34 AM" src="https://user-images.githubusercontent.com/9875439/80496182-730db300-892e-11ea-8965-def9eb5834b7.png">

**Comment by donavanbecker** [comment]
@twynne did that work?

**Comment by twynne** [comment]
Scared me initially... after restarting nearly all accessories disappeared from ConfigUI.  Fortunately they magically appeared again after a minute or so.

Yes, the ‘old’ accessories from Dyson platform are now gone.

Question regarding upgrading Homebridge itself... if I upgrade and things go wrong, then downgrade, are all pre-existing accessories restored?  I’m just trying to avoid having to reconfigure everything from scratch.  :)

**Comment by donavanbecker** [comment]
if you want to make sure that everything goes smoothly. I would create a backup of Homebridge before upgrading. Have you done that before in config UI?

Then upgrade..

What is your homebridge setup? environment?

**Comment by twynne** [comment]
Not sure I’ve needed to do a full backup of Homebridge before - just configs - but I can see the option and it seems straightforward.

Nothing fancy in terms of environment, just Homebridge on MacOS (native).

My main concern is that I have a number of scenes set up that are in turn used to automate.  If accessories are lost it all has to be re-established manually.

**Comment by donavanbecker** [comment]
if you update to the latest through the config, and you have issues. you can always open up a terminal window on your mac and execute this.
```
sudo npm install -g --unsafe-perm homebridge@0.4.53
```
as long as you don't mess with cache or anything you should be fine.

Let me know what you decide to do. Hope it works and you have no issues.

**Comment by twynne** [comment]
Ok, tried that and it didn’t go well.  Homebridge crashes with the following in logs:

Error: Cannot find module 'safe-buffer'
Require stack:
- /usr/local/lib/node_modules/homebridge/node_modules/dns-packet/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/multicast-dns/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Server.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Advertiser.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/AccessoryLoader.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/dns-packet/index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
[37m[4/28/2020, 5:18:35 PM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 1, Signal: null

**Comment by donavanbecker** [comment]
what version of node and all that are you on? also if you revert back is all good?

**Comment by twynne** [comment]
Nope, revert back also went wrong:

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'array-flatten'
Require stack:
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js',
    '/usr/local/lib/node_modules/homebridge/lib/cli.js',
    '/usr/local/lib/node_modules/homebridge/bin/homebridge'
  ]
}

I’m on node 13.12, npm 6.14.4.

Is it worth trying a restore of the entire Homebridge install (from the backup taken beforehand)?

**Comment by twynne** [comment]
Here's what's happening following restore (both the attempt to just roll back Homebridge, as well as a full restore from the backup created earlier):


internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'array-flatten'
Require stack:
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js',
    '/usr/local/lib/node_modules/homebridge/lib/cli.js',
    '/usr/local/lib/node_modules/homebridge/bin/homebridge'
  ]
}
[4/28/2020, 5:33:23 PM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[4/28/2020, 5:33:28 PM] [HB Supervisor] Restarting Homebridge...
[4/28/2020, 5:33:28 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -R
[4/28/2020, 5:33:28 PM] [HB Supervisor] Started Homebridge with PID: 97228
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'array-flatten'
Require stack:
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js
- /usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js
- /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/bonjour-hap/index.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js',
    '/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js',
    '/usr/local/lib/node_modules/homebridge/lib/cli.js',
    '/usr/local/lib/node_modules/homebridge/bin/homebridge'
  ]
}

**Comment by donavanbecker** [comment]
can you execute 
```
sudo hb-service rebuild
```
 and let me know the the log of that command?

**Comment by twynne** [comment]
I've raised this on the main Homebridge page... seriously wishing I'd left it alone now.  :(

**Comment by Supereg** [comment]
I may ask how did you install homebridge. It seems like npm didn't fetch all of the required dependencies?

**Comment by twynne** [comment]
> can you execute
> 
> ```
> sudo hb-service rebuild
> ```
> 
> and let me know the the log of that command?

ℹ Rebuilding for Node.js v13.12.0...

> node-pty-prebuilt-multiarch@0.9.0 install /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js


> node-pty-prebuilt-multiarch@0.9.0 postinstall /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
> node scripts/post-install.js

node-pty-prebuilt-multiarch@0.9.0 /usr/local/lib/node_modules/homebridge-config-ui-x/node_modules/node-pty-prebuilt-multiarch
✔ Rebuilt modules in /usr/local/lib/node_modules/homebridge-config-ui-x for Node.js v13.12.0.

**Comment by Supereg** [comment]
you may try stopping homebridge and then completely reinstalling homebridge with the following.

```
npm uninstall -g homebridge
npm install -g homebridge
```

**Comment by twynne** [comment]
Frankly it was a long time ago and I can't recall... it has literally been running for years - of course with upgrades, new platforms/accessories as things have changed.  I've never seen a problem this severe.

**Comment by twynne** [comment]
> you may try stopping homebridge and then completely reinstalling homebridge with the following.
> 
> ```
> npm uninstall -g homebridge
> npm install -g homebridge
> ```

Isn't this going to put 1.02 back??

**Comment by twynne** [comment]
Uninstall completed.  Attempt to reinstall gives:

npm WARN checkPermissions Missing write access to /private/etc
npm WARN enoent ENOENT: no such file or directory, open '/private/etc/package.json'
npm WARN etc No description
npm WARN etc No repository field.
npm WARN etc No README data
npm WARN etc No license field.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /private/etc
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/private/etc'
npm ERR!  [Error: EACCES: permission denied, access '/private/etc'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/private/etc'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/private/etc'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/homeserver/.npm/_logs/2020-04-28T16_47_26_594Z-debug.log

**Comment by Supereg** [comment]
It's a bit of an weird error, both of them. As this are dependencies missing of dependencies of dependencies. So nothing related to homebridge actually.

> Isn't this going to put 1.02 back??

Yes. You can also append `@0.4.53`. And maybe you need to prepend sudo

**Comment by Supereg** [comment]
> Uninstall completed. Attempt to reinstall gives:
> 
> npm WARN checkPermissions Missing write access to /private/etc
> npm WARN enoent ENOENT: no such file or directory, open '/private/etc/package.json'
> npm WARN etc No description
> npm WARN etc No repository field.
> npm WARN etc No README data
> npm WARN etc No license field.
> 
> npm ERR! code EACCES
> npm ERR! syscall access
> npm ERR! path /private/etc
> npm ERR! errno -13
> npm ERR! Error: EACCES: permission denied, access '/private/etc'
> npm ERR! [Error: EACCES: permission denied, access '/private/etc'] {
> npm ERR! stack: "Error: EACCES: permission denied, access '/private/etc'",
> npm ERR! errno: -13,
> npm ERR! code: 'EACCES',
> npm ERR! syscall: 'access',
> npm ERR! path: '/private/etc'
> npm ERR! }
> npm ERR!
> npm ERR! The operation was rejected by your operating system.
> npm ERR! It is likely you do not have the permissions to access this file as the current user
> npm ERR!
> npm ERR! If you believe this might be a permissions issue, please double-check the
> npm ERR! permissions of the file and its containing directories, or try running
> npm ERR! the command again as root/Administrator.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/homeserver/.npm/_logs/2020-04-28T16_47_26_594Z-debug.log

Yeah sorry forgot to mention the sudo before for both commands:

```
sudo npm uninstall -g homebridge
sudo npm install -g homebridge
```

**Comment by Supereg** [comment]
any success?

**Comment by twynne** [comment]
Yes, that's done it.  It appears to at least be running now (1.02) and a quick check suggests all accessories are back.  I'll need to dig deeper to check everything working properly.

**Comment by donavanbecker** [comment]
is your automation still working too?

**Comment by Supereg** [comment]
great

**Comment by twynne** [comment]
> is your automation still working too?

Appears to be. Still checking things.

**Comment by donavanbecker** [comment]
@twynne Glad it is!
@Supereg thanks for your knowledge!

**Comment by twynne** [comment]
> @twynne Glad it is!
> @Supereg thanks for your knowledge!

Thanks all (still wish I hadn’t!) 😁

**Comment by donavanbecker** [comment]
@twynne better to know than to not know...

**Comment by twynne** [comment]
It’s just a lot of hassle when my server goes wrong. It runs headless for one, so I have to remote into it. That causes added overhead trying to copy/paste across machines. And frankly I don’t really have the technical knowledge to remedy much of this myself... mostly hacking around based on what others have shared.

**Comment by donavanbecker** [comment]
@twynne totally understand! Glad it is working for you!
