### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by benzman81** [joe-ng/homebridge-dyson-link#127]
Since today I get following message and home bridge crashes:
```
[2021-1-14 9:22:01] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/markuskrueger/workspaces/gitrepos/homebridge-dyson-link/index.js:172:40)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
Dyson App is still working.

**Comment by tasict** [comment]
It's seem dyson change login api today!

**Comment by Caban-ru** [comment]
the same problem

**Comment by cwatkins94** [comment]
+1 for this issue

**Comment by jakobbohem** [comment]
:(

**Comment by BenMQ** [comment]
Looks like the authenticate api `/v1/userregistration/authenticate?country=` is returning 403 response with the body "error code: 1020"

I managed to work around by using the "old" config instead of account / password based authentication. See the first code snippet of [readme](https://github.com/joe-ng/homebridge-dyson-link#configuration) that sets the SSID and wifi password.

Remember to remove email and password from the config file (otherwise it prefers to use that)

**Comment by benzman81** [comment]
created pull request to add user agent to header #128

**Comment by joe-ng** [comment]
Thanks @benjamin87 ! Just merged that and released v2.5.5 for that

**Comment by onefish2** [comment]
I restarted homebridge today with the 2.5.5 plugin and now I am seeing this error.

**Comment by Caban-ru** [comment]
> I restarted homebridge today with the 2.5.5 plugin and now I am seeing this error.

yes((

**Comment by francisschmaltz** [comment]
It looks like Dyson is putting the API behind Cloudflare and restricting this header agent. Perhaps we can move the header to the config to allow easy changing?

**Comment by francisschmaltz** [comment]
Sending with a user agent of `fsdghasd` works. It seems that they're specifically restricting user agents. Something I've seen work elsewhere is setting the headers of the request to the same ones that iOS/Android apps use. That way if they want to restrict specific headers, it requires an update to an app and there is time to change it here.

**Comment by benzman81** [comment]
Fixed for now with pull request #131 using android user agent.

**Comment by sment1337** [comment]
I am sill seeing this: 

```
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:180:40)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

its not the "token < " error as above but I wonder is this is something else?

**Comment by benzman81** [comment]
@sment1337 they changed it again. I create pull request #131  so that @joe-ng can merged it to fix this.

**Comment by sment1337** [comment]
Thank you!
Thomas Charisoulis,
sment1337@gmail.com

**Comment by joe-ng** [comment]
Thanks @benzman81 ! 
just released 2.5.6 for that
