### ISSUE TITLE
SyntaxError: Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by mlaine2013** [joe-ng/homebridge-dyson-link#132]
1/29/2021, 9:56:14 PM SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-dyson-link/index.js:180:40)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by joe-ng** [comment]
Thanks to @benzman81 fix in #127 , it may get fixed 
Please try 2.5.6 and see if that works for you

**Comment by mlaine2013** [comment]
So far so good. Thank you!

**Comment by amanbaig123** [comment]
Still have this issue while running 2.5.6

**Comment by PatrickDollard** [comment]
Also having this issue.

**Comment by eifeldj** [comment]
@joe-ng  Has this been solved as I am still getting this issue...

**Comment by devlinandrew** [comment]
Same issue here.
