### ISSUE TITLE
Still API 400 error, blank page in credentials website (v2.0.1)

### ISSUE THREAD

**Issue by ghost** [joe-ng/homebridge-dyson-link#141]
After 2.0.1 update I still get the API 400 error. After typing in my details in the credentials website and I click "Next", the page goes blank and no info comes up (ERR_CONNECTION_REFUSED browser error).

I find this in the logs:

```
[5/23/2021, 12:27:22 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
    at Decipheriv.update (internal/crypto/cipher.js:157:11)
    at Request._callback (/homebridge/node_modules/homebridge-dyson-pure-cool/src/credentials-generator-website.js:449:54)
    at Request.self.callback (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-dyson-pure-cool/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
```

Any ideas or suggestions?

**Comment by ghost** [comment]
So sorry. Wrong project... I will close this now and go to sleep. Sorry again.
