### ISSUE TITLE
DYSON GIVING ERROR

### ISSUE THREAD

**Issue by agowda76** [joe-ng/homebridge-dyson-link#142]
HI,

I Like the plugin, worked fine for a day, but then started giving errors and HB keeps restarting continuously, so basically, every time install the plugin HB stops working.

I'm getting this error right now, don't know what sense to make out of it

SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:180:40)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

It may be an issue of the platform name or platform, cause once I just did a add platform and save it worked until I restarted HB and then it was gone again.

Anything to make this work without any issues would be great. hope the feedback helps.

Thanks
AG

**Comment by agowda76** [comment]
Looks like the issue is with Dyson account password, If you comment the password or take out that line, the HB works fine also showing all the options of Dyson device, but from my device. just like a place holder. hope this helps you to solve the issue.

**Comment by redrohX** [comment]
Same problem here. 
```
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-dyson-link/index.js:180:40)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Removing the password removes indeed the error, but then obviously the device is not added to accessories.

**Comment by MariellevDijk** [comment]
This is happening with me too, removing password keeps homekit out of it's bootloop. 

    [6/9/2021, 4:22:04 PM] [DysonPlatform] Initializing DysonPlatform platform...
    [6/9/2021, 4:22:04 PM] [DysonPlatform] Finished launching. Start to create accessory from config
    [6/9/2021, 4:22:04 PM] [DysonPlatform] Dyson email/pass not found, v2 devices may not work
    [6/9/2021, 4:22:04 PM] [DysonPlatform] Missing password for device with serial number [serial], devices found on your account:

**Comment by atomicmaximaze** [comment]
Same here... hopefully someone has an idea or it'll be fixed with an update :o

`SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:180:40)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

**Comment by giss69** [comment]
same problem:(

**Comment by surfing-IT** [comment]
Same problem here.  Thanks for looking into it

**Comment by Andavin** [comment]
Removed my account password from the config and for some reason it completely started working again. Hopefully it stays that way, but may be a fix for others here also

**Comment by zachwaterson** [comment]
It looks like Dyson is rolling out two factor authentication, which this plugin does not support. I switched to this plugin, and it's working great!

https://github.com/lukasroegner/homebridge-dyson-pure-cool
