### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by duytuanphi** [joe-ng/homebridge-dyson-link#143]
Hi, could anybody help me with this. When ever I config the accessories (IP, Serial, Pass), Homebridge stop working
`[6/14/2021, 1:42:50 PM] [HB Supervisor] Restarting Homebridge...
[6/14/2021, 1:42:50 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[6/14/2021, 1:42:50 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 3603
Initializing HAP-NodeJS v0.9.4...
[6/14/2021, 1:42:51 PM] Loaded config.json with 0 accessories and 2 platforms.
[6/14/2021, 1:42:51 PM] Loaded 0 cached accessories from cachedAccessories.
[6/14/2021, 1:42:51 PM] ---
[6/14/2021, 1:42:51 PM] Loaded plugin: homebridge-config-ui-x@4.41.1
[6/14/2021, 1:42:51 PM] Registering platform 'homebridge-config-ui-x.config'
[6/14/2021, 1:42:51 PM] ---
[6/14/2021, 1:42:51 PM] Loaded plugin: homebridge-dyson-link@2.5.6
homebridge API version: 2.7
[6/14/2021, 1:42:51 PM] Registering platform 'homebridge-dyson-link.DysonPlatform'
[6/14/2021, 1:42:51 PM] ---
[6/14/2021, 1:42:51 PM] Loading 2 platforms...
[6/14/2021, 1:42:51 PM] [Config] Initializing config platform...
[6/14/2021, 1:42:51 PM] [Config] Running in Service Mode
[6/14/2021, 1:42:51 PM] [DysonPlatform] Initializing DysonPlatform platform...
[6/14/2021, 1:42:51 PM] [DysonPlatform] Finished launching. Start to create accessory from config
Preparing Advertiser for 'Homebridge 233E 93D4' using bonjour-hap backend!
Setup Payload:
X-HM://0023NU3Z4980O
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 115-96-448 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 233E 93D4' using bonjour-hap backend!
[6/14/2021, 1:42:51 PM] Homebridge v1.3.4 (Homebridge 233E) is running on port 51221.
[6/14/2021, 1:42:51 PM] SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:180:40)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[6/14/2021, 1:42:51 PM] Got SIGTERM, shutting down Homebridge...
[6/14/2021, 1:42:56 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/14/2021, 1:43:01 PM] [HB Supervisor] Restarting Homebridge...`

**Comment by Andavin** [comment]
I have this exact same issue as of yesterday or today. Maybe Dyson updated something that's breaking the HomeBridge plugin?
EDIT: Just removed my account password and for some reason it started completely working again.

**Comment by eddie1590** [comment]
> I have this exact same issue as of yesterday or today. Maybe Dyson updated something that's breaking the HomeBridge plugin?
> EDIT: Just removed my account password and for some reason it started completely working again.

Hey there, which plug-in are you using? The new Dyson plugin published on May of this year? I’m using it on Hoobs Homebridge but I cant get my Dyson fans to appear on homekit. How are you getting yours to still work if I may ask?

**Comment by PierreBrisorgueil** [comment]
Same error, remove pwd don’t fix the bug on my side.

**Comment by eifeldj** [comment]
Same issue here

**Comment by petergeneric** [comment]
I think this is because Dyson have changed their authentication logic. This plugin was crashing homebridge for me too, but since this plugin doesn't seem to be actively maintained anymore I switched to https://github.com/lukasroegner/homebridge-dyson-pure-cool which is working perfectly for me.
