### ISSUE TITLE
Connection refused: Bad username or password

### ISSUE THREAD

**Issue by chodonw** [joe-ng/homebridge-dyson-link#19]
When I start homebridge it told me bad username or password and shut down but I confirm them in manual many times. I used password which is product wifi password because I see the introduction password is 8 character and can be found in manual.I also got my dyson MQTT password with mqtt client.I try it as password still didn't work.

Here is some information of my raspberry pi
Node : 8.9.4
npm: 5.6.0
homebridge:0.4.38

[2018-2-13 06:36:08] [DysonPlatform] Finished launching. Start to create accessory from config
[2018-2-13 06:36:08] [DysonPlatform] Dyson IP:10.10.10.96 Serial Number:DYSON-PE6-US-JJA0049A-455
[2018-2-13 06:36:08] [DysonPlatform] Air Quality Sensitivity (Default is 1): 1
[2018-2-13 06:36:08] [DysonPlatform] Device serial number format valids
[2018-2-13 06:36:08] [DysonPlatform] Device cached. Try to update this
[2018-2-13 06:36:08] [DysonPlatform] Init Sensor for Dyson
[2018-2-13 06:36:08] [DysonPlatform] Init Fan State for Dyson
[2018-2-13 06:36:08] [DysonPlatform] Heat Available. Add Heat button and jet control
[2018-2-13 06:36:08] Homebridge is running on port 51826.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: Bad username or password
    at MqttClient._handleConnack (/usr/local/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:877:15)
    at MqttClient._handlePacket (/usr/local/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:319:12)
    at work (/usr/local/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/local/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/usr/local/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/usr/local/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Writable.write (/usr/local/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

Thank you very much !!

**Comment by joe-ng** [comment]
Maybe you can check if your IP of the device was correct? Was that 10.10.10.96? 
Also, would your router block any mqtt connection?

**Comment by chodonw** [comment]
I'm sure the IP is correct and the router won't block mqtt because it works ok with "npm homebridge-dyson-fan".Any idea or any way to check further more log? Many thanks again!

**Comment by Manguera** [comment]
hi there. i have the same issue using a dyson hot + cool link. is there any advanced debug possible to check what went wrong?

**Comment by joe-ng** [comment]
@AndrewCMartin has helped to adapt the new way to configure the username/password from your dyson account. so you may try the v2 to see if that works

**Comment by Menghongli** [comment]
Has any has a solution for this issue, I've tried both version of configuration and it all failed at this error, where would I find out whether my device is v2 or not?

**Comment by Menghongli** [comment]
Just in case if anyone else has the same issue, you need to update the serial number from:
- `DYSON-SZ1-AU-JEAxxxx-xxx`
to
- `SZ1-AU-JEAxxxx`
