### ISSUE TITLE
Crashing homebridge 

### ISSUE THREAD

**Issue by JonathanFStewart** [joe-ng/homebridge-dyson-link#27]
I keep seeing the following error when trying to do anything with my cool link air purifer with home bridge on a raspberry pi.

> /usr/lib/node_modules/homebridge-dyson-link/DysonFanState.js:9
        this._fan = newState["product-state"]["fmod"] === "FAN" || newState["product-state"]["fmod"] === "AUTO";
                                             ^
TypeError: Cannot read property 'fmod' of undefined
    at DysonFanState.updateState (/usr/lib/node_modules/homebridge-dyson-link/DysonFanState.js:9:46)
    at MqttClient.DysonLinkDevice.mqttClient.on (/usr/lib/node_modules/homebridge-dyson-link/DysonLinkDevice.js:69:39)
    at MqttClient.emit (events.js:180:13)
    at MqttClient._handlePublish (/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:940:12)
    at MqttClient._handlePacket (/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:305:12)
    at work (/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/usr/lib/node_modules/homebridge-dyson-link/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/usr/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/usr/lib/node_modules/homebridge-dyson-link/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:646:20)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:578:20)

**Comment by JonathanFStewart** [comment]
Resolved by updating fan firmware
