### ISSUE TITLE
Homebridge crashes

### ISSUE THREAD

**Issue by m11rphy** [joe-ng/homebridge-dyson-link#35]
Hi Joe

When launching homebridge it is getting so far then crashing with the below error, any help would be greatly appreciated 

Error:

[5/5/2018, 11:36:18 AM] [DysonPlatform] Finished launching. Start to create accessory from config
[5/5/2018, 11:36:18 AM] [DysonPlatform] Dyson email/pass not found, v2 devices may not work
[5/5/2018, 11:36:18 AM] [DysonPlatform] Dyson Fan IP:192.168.1.23 Serial Number:DYSON-NC8-UK-HDA0361A-469
[5/5/2018, 11:36:18 AM] [DysonPlatform] Air Quality Sensitivity (Default is 1): 1
[5/5/2018, 11:36:18 AM] [DysonPlatform] Device serial number format valids
[5/5/2018, 11:36:18 AM] [DysonPlatform] Device not cached. Create a new one
[5/5/2018, 11:36:18 AM] [DysonPlatform] Init Sensor for Dyson Fan
[5/5/2018, 11:36:18 AM] [DysonPlatform] Init Fan State for Dyson Fan
[5/5/2018, 11:36:18 AM] [DysonPlatform] Night mode button is added
/usr/local/lib/node_modules/homebridge-dyson-link/DysonLinkAccessory.js:128
            .on("get", this.device.getFilterChange.bind(this.device));
            ^

TypeError: Cannot read property 'on' of undefined
    at DysonLinkAccessory.initFanState (/usr/local/lib/node_modules/homebridge-dyson-link/DysonLinkAccessory.js:128:13)
    at new DysonLinkAccessory (/usr/local/lib/node_modules/homebridge-dyson-link/DysonLinkAccessory.js:29:14)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:85:37)
    at Array.forEach (native)
    at getDevicesFromAccount (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:50:49)
    at DysonPlatform.getDevicesFromAccount (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:118:13)
    at API.DysonPlatform.api.on (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:49:26)
    at emitNone (events.js:86:13)
    at API.emit (events.js:185:7)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by joe-ng** [comment]
that function call was from the homebridge API. 
can you try to update your homebridge to latest version to see if that works?

**Comment by m11rphy** [comment]
Had to reinstall macOS , will try again now

**Comment by m11rphy** [comment]
All working great, thank you so much for this plugin its great

**Comment by joe-ng** [comment]
Good to know, thanks!
