### ISSUE TITLE
Error when trying to run homebridge

### ISSUE THREAD

**Issue by livefeed** [joe-ng/homebridge-dyson-link#50]
[8/2/2018, 4:13:27 PM] [DysonPlatform] Night mode button is added
HAP Warning: Characteristic 000000BF-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000B7-0000-1000-8000-0026BB765291. Adding anyway.
internal/crypto/hash.js:58
    throw new ERR_INVALID_ARG_TYPE('data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:58:11)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:72:72)
    at Array.forEach (<anonymous>)
    at getDevicesFromAccount (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:50:49)
    at DysonPlatform.getDevicesFromAccount (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:121:13)
    at API.DysonPlatform.api.on (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:49:26)
    at API.emit (events.js:187:15)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by livefeed** [comment]
Anyone? I just can't get this to run.

**Comment by joe-ng** [comment]
did you input password explicitly for the device? Or did you use the dyson account to connect?
if that's latter, you will need to make sure you have input the correct country code in the your config(assuming you have verified you have used the correct email and password)

**Comment by livefeed** [comment]
@joe-ng I just can't get this to work, here is my error;


[10/2/2018, 12:38:07 PM] [DysonPlatform] Dyson IP:10.0.1.167 Serial Number:DYSON-NM7-US-XXXXXX-475
[10/2/2018, 12:38:07 PM] [DysonPlatform] Device serial number format valids
[10/2/2018, 12:38:07 PM] [DysonPlatform] Device cached. Try to update this
[10/2/2018, 12:38:07 PM] [DysonPlatform] Init Sensor for Dyson
[10/2/2018, 12:38:07 PM] [DysonPlatform] Init Fan State for Dyson
[10/2/2018, 12:38:07 PM] [DysonPlatform] Auto switch found. Remove this now
[10/2/2018, 12:38:07 PM] [DysonPlatform] Night mode button is added
HAP Warning: Characteristic 000000BF-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000B7-0000-1000-8000-0026BB765291. Adding anyway.
Unhandled Error Detected :  TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:58:11)
    at config.accessories.forEach (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:73:72)
    at Array.forEach (<anonymous>)
    at getDevicesFromAccount (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:50:49)
    at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:201:25)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Restarting homebridge due to an error
restarting...
shutting down...
shutting down servers...
starting next hub...
["/usr/local/bin/homebridge"]
waiting for exit...

**Comment by Mirxx** [comment]
I have got problem starting Homebridge:

homebridge
[2019-3-22 10:41:37] Loaded config.json with 2 accessories and 1 platforms.
[2019-3-22 10:41:37] ---
[2019-3-22 10:41:38] Loaded plugin: homebridge-dyson-link
homebridge API version: 2.3
[2019-3-22 10:41:38] Registering platform 'homebridge-dyson-link.DysonPlatform'
[2019-3-22 10:41:38] ---
[2019-3-22 10:41:39] Loaded plugin: homebridge-mi-airpurifier
[2019-3-22 10:41:39] ---
[2019-3-22 10:41:39] Loading 1 platforms...
[2019-3-22 10:41:39] [DysonPlatform] Initializing DysonPlatform platform...
[2019-3-22 10:41:39] Loading 2 accessories...
/usr/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
