### ISSUE TITLE
index error when trying to start homebridge.

### ISSUE THREAD

**Issue by cartonj001** [joe-ng/homebridge-dyson-link#51]
I can't figure out why it is not working.

usr/lib/node_modules/homebridge/lib/api.js:50
  if (name.indexOf('.') == -1) {
           ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:285:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by ashman247** [comment]
What did you do to resolve the issue? I'm getting the same error.

**Comment by StayFlyEatFries** [comment]
Does anyone have a fix for this?
