### ISSUE TITLE
Error with JSON parsing

### ISSUE THREAD

**Issue by NewBends** [joe-ng/homebridge-dyson-link#52]
After I installed the plugin and made the required changes to the config.json file, I ended up with the following error when trying to launch homebridge:

[8/10/2018, 3:27:45 AM] There was a problem reading your config.json file.
[8/10/2018, 3:27:45 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[8/10/2018, 3:27:45 AM] 
/usr/lib/node_modules/homebridge/lib/server.js:213
    throw err;
    ^

SyntaxError: Unexpected token / in JSON at position 119
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:207:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

It looks like the problem is with line 7 at "platforms": which makes no sense.  Any suggestions?  Homebridge launched fine before I installed the plugin.  Any thoughts?

**Comment by NewBends** [comment]
I went back to a clean config file and get homebridge to launch again.  If I add the platforms, it's fine.  As soon as I add the Accessory code it stops.  What am I doing wrong?  Below is the config info

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
	"platforms": [
        {
            "platform" : "DysonPlatform",
            "name" : "Dyson"
        }
    ]
    	"accessories":[
    	{
          "ip": "192.168.1.124",
          "displayName": "Dyson TP02",
          "serialNumber": "DYSON-xxx-US-xxx1836A-475",
          "password": "xxxxxxxxx",
        },
	]
}


Terminal output: 

SyntaxError: Unexpected string in JSON at position 265
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:207:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:28:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by joe-ng** [comment]
you need to put the accessories in the same element as the dyson platform, i.e. 

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform": "DysonPlatform",
            "name": "Dyson",
            "accessories": [
                {
                    "ip": "192.168.1.124",
                    "displayName": "Dyson TP02",
                    "serialNumber": "DYSON-xxx-US-xxx1836A-475",
                    "password": "xxxxxxxxx"
                }
            ]
        }
    ]
}
