### ISSUE TITLE
EADDRINUSE

### ISSUE THREAD

**Issue by ShermanThruGA** [joe-ng/homebridge-dyson-link#69]
I'm getting the error below when I try to run Homebridge. Do you know what needs to be modified to resolve this? My Homebridge installation is on a Mac.

(node:77642) [DEP0025] DeprecationWarning: sys is deprecated. Use util instead.
Error: listen EADDRINUSE :::8765
    at Server.setupListenHandle [as _listen2] (net.js:1327:14)
    at listenInCluster (net.js:1375:12)
    at Server.listen (net.js:1462:7)
    at new ServerPlatform (/usr/local/lib/node_modules/homebridge-server/index.js:532:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:324:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by ShermanThruGA** [comment]
There was another process that I needed to kill first. That fixed it.
