### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by PrzemyslawKlys** [joe-ng/homebridge-dyson-link#90]
I've had Dyson up and running for weeks/months without an issue. Today I've noticed my TV turning itself up and when I turned it off it would be up again. 

It seems that while my TV was up it was Dyson doing the work. 
```
Jun 21 08:29:01 evoservices homebridge[3074]: [6/21/2019, 8:29:01 AM] SyntaxError: Unexpected token < in JSON at position 0
Jun 21 08:29:01 evoservices homebridge[3074]:     at JSON.parse (<anonymous>)
Jun 21 08:29:01 evoservices homebridge[3074]:     at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:179:40)
Jun 21 08:29:01 evoservices homebridge[3074]:     at emitNone (events.js:111:20)
Jun 21 08:29:01 evoservices homebridge[3074]:     at IncomingMessage.emit (events.js:208:7)
Jun 21 08:29:01 evoservices homebridge[3074]:     at endReadableNT (_stream_readable.js:1064:12)
Jun 21 08:29:01 evoservices homebridge[3074]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
Jun 21 08:29:01 evoservices homebridge[3074]:     at process._tickCallback (internal/process/next_tick.js:180:9)
Jun 21 08:29:01 evoservices homebridge[3074]: [6/21/2019, 8:29:01 AM] Got SIGTERM, shutting down Homebridge...
```

You may want to add some logic try/catch for parser so it doesn't crash the whole home bridge and affect other devices.

Thank you, and thank you for your work.

**Comment by giss69** [comment]
Hi,
i've the same issue hier.
Did you solved you problem?

**Comment by PrzemyslawKlys** [comment]
I've edited some code to prevent the plugin from crashing however I believe this is related to wrong return from Dyson. 

I started updating home bridge all plugins and suddenly it went away. So my guess it must be something on Dyson's end that's causing JSON requests to crash because there's no try/catch logic. I'm too weak in JavaScript area/Homebridge dev to fix stuff like that. But I should try and find out because there's a lot of areas you are on your own.

**Comment by giss69** [comment]
thank you for a quick replay!
your HB doesn't crash anymore but you do still have an error?

**Comment by PrzemyslawKlys** [comment]
No, the error went away so I've removed my modifications because as far as I could tell the "fix" I did prevent crashes but it didn't get Dyson to work. That's why I believe the problem is on Dyson's (vendor) end and not something we can fix. We can only fix the behavior of the plugin to stop crashing HB and impacting other devices. In my case, it was turning on my SONY TV and driving me crazy.

**Comment by giss69** [comment]
appreciate you help!
it's pretty curios, because it worked all the time and suddenly, without changing anything, stoppt working.
Ich guess it's Dyson server problem.

**Comment by alecc131** [comment]
I am all of a sudden having problems too. Maybe involving Dyson. Homebridge stuck “Updating”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by epheterson** [comment]
I'm hitting this with my dyson plugin as well, interested in how to fix. So far I've had to remove the plugin from my config to get homebridge to run.

```
[1/14/2021, 1:33:20 PM] SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:179:40)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by epheterson** [comment]
The latest update fixes the issue! I'm switching back from "Homebridge Dyson Pure Cool" because this plugin publishes a fan service which is easier to interact with than the air filter service in Home App.

**Comment by epheterson** [comment]
Wow it came back today! Crash looping with the same error as before.
