### ISSUE TITLE
Error after restarting homebridge

### ISSUE THREAD

**Issue by onefish2** [joe-ng/homebridge-dyson-link#95]
I am getting this error out of the blue after running this plug in with a HP02 for many months. I updated another plugin, restarted homebridge and now homebridge crashes with this error:

SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>:null:null)
at IncomingMessage.res.on (/usr/local/lib/node_modules/homebridge-dyson-link/index.js:179:40)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
[9/14/2019, 10:03:56 PM] Got SIGTERM, shutting down Homebridge...

Here is my config:

{
            "platform": "DysonPlatform",
            "name": "DysonPlatform",
            "email": "user@example.com",
            "password": "password",
            "country": "US",
            "accessories": [
                {
                    "ip": "192.168.0.x",
                    "displayName": "Dyson HP02",
                    "serialNumber": "XX1-US-XXX1234Z",
                    "password": "password",
                    "nightModeVisible": false,
                    "focusModeVisible": true,
                    "autoModeVisible": true
                }
            ]
        },

**Comment by HammerAce42** [comment]
I am seeing the same issue. I have an HP04 and two Hot + Cool Link machines.

**Comment by HomeTech02** [comment]
Exact same problem here. Was working perfectly up until now. I'm guessing Dyson changed something with their API

**Comment by HomeTech02** [comment]
So the fix is to change the following lines in the "index.js" file:

Line 144: change link to "appapi.cp.dyson.com"
Line 146 (if you're in China): change link to "appapi.cp.dyson.cn"

**Comment by onefish2** [comment]
Thank you @HomeTech for that quick update. That worked.

**Comment by joe-ng** [comment]
Thanks! just updated the package accordingly

**Comment by ifeign** [comment]
After you updated the server, I can no longer control my fan. The accessory appears in Homekit and the Homebridge logs, but the fan does nothing.
